export const SliderRentUsers = [
    // {id:1,img:"/Allphoto/user1.jpg",name:"ماندانا تبریزی",address:"املاک ولیعصر",reng:"امتیاز ۴ از ۵"},
    // {id:2,img:"/Allphoto/user2.jpg",name:"رز دانش",address:"املاک سبز",reng:"امتیاز ۴/۸ از ۵"},
    // {id:3,img:"/Allphoto/user3.jpg",name:"زیبا تاجدار",address:"املاک فرشته",reng:"امتیاز ۴ از ۵"},
    // {id:4,img:"/Allphoto/user4.jpg",name:"علی پرتو",address:"املاک توسی",reng:"امتیاز ۵ از ۵"},
    // {id:5,img:"/Allphoto/user1.jpg",name:"ماندانا تبریزی",address:"املاک ولیعصر",reng:"امتیاز ۴ از ۵"},
    // {id:6,img:"/Allphoto/user2.jpg",name:"رز دانش",address:"املاک سبز",reng:"امتیاز ۴/۸ از ۵"},
    // {id:7,img:"/Allphoto/user3.jpg",name:"زیبا تاجدار",address:"املاک فرشته",reng:"امتیاز ۴ از ۵"},
    // {id:8,img:"/Allphoto/user4.jpg",name:"علی پرتو",address:"املاک توسی",reng:"امتیاز ۵ از ۵"},


    { id: 1, name: "پویا وحید", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/1.jpg" },
    { id: 2, name: "حامد خواجوی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/2.jpg" },
    { id: 3, name: "دریا دلنواز", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/3.jpg" },
    { id: 4, name: "علیرضا بیکو", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/4.jpg" },
    { id: 5, name: "مانا قنبری", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/5.jpg" },
    { id: 6, name: "پیروز فرخی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/6.jpg" },
    { id: 7, name: "نیما سودگر", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/7.jpg" },
    { id: 8, name: "سورنا رضایی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/not.png" },
    { id: 9, name: "محمدرضا ایروانی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/9.png" },
    { id: 10, name: "مهرناز بهادری", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/10.jpg" },
    { id: 11, name: "سارا شریفی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/11.png" },
    { id: 12, name: "علی زکیه", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/12.jpg" },
    { id: 13, name: "ابرج خلیلی‌فر", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/13.jpg" },
    { id: 14, name: "مهرداد اسلامی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/14.jpg" },
    { id: 15, name: "حسام رضایی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/15.jpg" },
    { id: 16, name: "آناستازیا نیکولیک", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/16.jpg" },
    { id: 17, name: "صدف مصطفوی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/17.jpg" },
    { id: 18, name: "فاطمه ایازی", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/18.jpg" },
    { id: 19, name: "آنا بویوف", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/19.jpg" },
    { id: 20, name: "نوشین توکلیان", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/20.jpg" },
    { id: 21, name: "احمد بن یانه", role: "املاک طوسی", rating: "امتیاز ۴ از ۵", image: "/ALLADVICER/21.jpg" },
];

