export const ArayAllFilters = [
  {
    id: 1,
    name: "اتاق خواب",
    text: "هر تعداد",
    text1: "بدون اتاق",
    text2: "۱",
    text3: "۲",
    text4: "۳",
    text5: "۴",
    text6: "+۵",
  },
  {
    id: 2,
    name: "پارکینگ",
    text: "هر تعداد",
    text1: "ندارد",
    text2: "۱",
    text3: "۲",
    text4: "+۳",
  },
  {
    id: 3,
    name: "انباری",
    text: "هر تعداد",
    text1: "ندارد",
    text2: "۱",
    text3: "۲",
    text4: "+۳",
  },
  {
    id: 4,
    name: "سرویس بهداشتی",
    text: "هر تعداد",
    text1: "ندارد",
    text2: "۱",
    text3: "۲",
    text4: "۳",
    text5: "+۴",
  },
  {
    id: 5,
    name: " نوع سرویس بهداشتی",
    text: "مهم نیست ",
    text1: "ایرانی",
    text2: "فرنگی",
    text3: "هر دو",
  },
  {
    id: 6,
    name: "   آسانسور",
    text: "مهم نیست ",
    text1: "۱",
    text2: "۲",
    text3: "+۳",
  },
  {
    id: 7,
    name: "طبقه",
    text: "مهم نیست ",
    text1: "همکف",
    text2: "۱",
    text3: "۲",
    text4: "۳",
    text5: "۴",
    text6: "+۵",
  },
  {
    id: 8,
    name: " سیستم سرمایش",
    text: "مهم نیست ",
    text1: "کولر آبی",
    text2: "اسپلیت",
    text3: "فن کوئل",
    text4: "چیلر",
  },
  {
    id: 9,
    name: "  سیستم گرمایش",
    text: "مهم نیست ",
    text1: "مرکزی ",
    text2: "اسپلیت",
    text3: "شومینه ",
    text4: "از کف",
    text5: "رادیاتور",
  },
  {
    id: 10,
    name: " جنس کف ",
    text: "مهم نیست ",
    text1: " سنگ",
    text2: "سرامیک",
    text3: "پارکت ",
    text4: "لمینت",
    text5: "موزائیک",
  },
];
